### ISSUE TITLE
Nuxt 3 & vue loading overlay 6

### ISSUE THREAD

**Issue by Ischafak** [ankurk91/vue-loading-overlay#111]
Hi, when i try to add this component to nuxt i am facing with a problem.

Cannot read properties of undefined (reading '_c')

vue-loading-overlay": "^6.0", this is my version

```js
import Loading from 'vue-loading-overlay';
import 'vue-loading-overlay/dist/css/index.css';


export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('loading', Loading)
})
```

Is there any possibility to use this component with nuxt3

**Comment by Ischafak** [comment]
I need slot because of that i am trying to add as a component

**Comment by ankurk91** [comment]
I will check the compatibility tomorrow and post back here

**Comment by Ischafak** [comment]
i will be very happy if you check it

**Comment by ankurk91** [comment]
I could not reproduce this issue on fresh Nuxt 3.0.0-rc.12

**Comment by nupamore** [comment]
I manage the private component package of the company project by mapping several libraries. Only this project caused post-build problems. Currently, I solved the problem by using `src` instead of taking the `dist` of this library.
I didn't have time to take a closer look, but this library might not work properly on vite because it was built and deployed as a webpack.

**Comment by ankurk91** [comment]
If someone can share a minimal reproduction of the issue, would be helpful
