### ISSUE TITLE
Suggestion about z-index

### ISSUE THREAD

**Issue by luiseok** [ankurk91/vue-loading-overlay#30]
Hello. @ankurk91 
First of all, thank you for making and sharing this component. Thanks to this, I've been able to increase productivity.

I have one suggestion about z-index.
Currently, I am adjusting the z-index value of overlay through the external style sheet for z-index issue, which would be nice if I could get it through the props and use it.
If you agree to this, I'll make a pull request.
I'll be waiting for the reply. Thank you.

**Comment by ankurk91** [comment]
Thanks for connecting.
I can understand your concerns but if you make a PR for `z-index` prop then people would ask to customize each every css property via props.

I can release a new version with increased `z-index`, but not sure the number. Different libraries have different z-index for their overlay. 
I think `9999` would be enough.

I believe your issue is related to this one
https://github.com/ankurk91/vue-loading-overlay/issues/26

**Comment by luiseok** [comment]
Thank you for your quick response.

As you mentioned, there is a problem when used with other libraries.
Using the UI Component Library that dynamically sets the z-index will cause problems even if you specify the z-index value you want.
Instead of fixing the z-index to 9999, it would be nice if you could control the z-index value directly through props, leaving the default z-index at 999.
The current code can be controlled with props for color, height, width, and background-color. If only one more z-index is added here, it would be better 😄

**Comment by ankurk91** [comment]
Closed with v3.2.0
