### ISSUE TITLE
vue-loading-orverlay internet explorer

### ISSUE THREAD

**Issue by renanbarbalho** [ankurk91/vue-loading-overlay#32]
Hi folks,
My application needs to execute under internet explorer but i when opening in internet explorer the vue-loading-overlay animation doesn't works , are there anything to solve the loading in internet explorer versions?

**Comment by ankurk91** [comment]
Hi, 
Thanks for reaching out 
Unfortunately this package does not fully support IE.
It is already mentioned in readme.
https://github.com/ankurk91/vue-loading-overlay/blob/master/README.md#browser-support

This package is using animated svg since v3.
You may try v2.x.
Or you can supply your own loading component via slots.

**Comment by renanbarbalho** [comment]
Do you have any sample to fixit using slots?

**Comment by ankurk91** [comment]
I dont have access to Windows PC.
I can't write code and test against IE.
I believe you can replace the svg with a simple test message or an image tag with gif.

Checkout examples

**Comment by renanbarbalho** [comment]
Thank you for your previous answers.
I understood the solution using slot but now I have another question, Is possible define Slot to use using component in tag notation? Like:

`<loading
      :active="isLoading"
      :loader="loading.loader"
      :color="loading.color"
      :can-cancel="false"      
slots="true"
    />`

**Comment by renanbarbalho** [comment]
Thanks for your help! I found a solution.

**Comment by powolnymarcel** [comment]
Too bad you didn't share your solution..
