### ISSUE TITLE
disable tab navigation while loading is showing

### ISSUE THREAD

**Issue by empresarrollo** [ankurk91/vue-loading-overlay#9]
It would be great if you can capture the tab key so the user cannot go to some inputs or links with the tab key while the loading is enabled

**Comment by ankurk91** [comment]
I tried various solution but none of worked.
I gone through packages like https://github.com/theKashey/vue-focus-lock
but their solution is not clean and a bit hacky.
I have also gone through bootstrap [model](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js) component, because it is already doing the same. But could not figure out how they are doing.

**Comment by ankurk91** [comment]
@empresarrollo
I have made this feature, i haven't released it, need more testing.
See the commit https://github.com/ankurk91/vue-loading-overlay/commit/063cceee1d4800ea986b2e845fdb85263cff2d29

Will invest more time this weekend.

**Comment by ankurk91** [comment]
Released v2.2.0
